-- Run this in the Supabase SQL Editor

create table if not exists public.product_videos (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  product_name text not null,
  instagram_url text not null,
  thumbnail_url text,
  created_at timestamptz not null default now(),
  constraint product_videos_product_fk
    foreign key (product_id)
    references public.products(id)
    on delete cascade
);

-- Optional: make sure product_id is indexed for faster lookups
create index if not exists product_videos_product_id_idx
on public.product_videos (product_id);

create index if not exists product_videos_created_at_idx
on public.product_videos (created_at desc);

-- Allow authenticated admin users to insert/update/delete rows
create policy "Admins can manage product videos"
on public.product_videos
for all
to authenticated
using (true)
with check (true);

-- Allow public read access for the storefront
create policy "Public can view product videos"
on public.product_videos
for select
to public
using (true);

-- Create a public storage bucket for video thumbnails
insert into storage.buckets (id, name, public)
values ('video-thumbnails', 'video-thumbnails', true)
on conflict (id) do nothing;

-- Storage policies
create policy "Admins can upload product thumbnails"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'video-thumbnails');

create policy "Admins can update or delete product thumbnails"
on storage.objects
for update, delete
to authenticated
using (bucket_id = 'video-thumbnails');

create policy "Anyone can view product thumbnails"
on storage.objects
for select
to public
using (bucket_id = 'video-thumbnails');
